version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sleep-tracker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hdh3pxgu0he5"
s3_prefix = "sleep-tracker"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
